name: Deploy to GitHub Pages

on:
  push:
    branches: 'main' # Se ejecutará cada vez que hagas push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Configurado para usar Node 24
          cache: yarn      # Cambiado a Yarn para optimizar el tiempo de instalación

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Instala exactamente lo que dice tu yarn.lock

      - name: Build project
        run: yarn build # Comando de Yarn para compilar tu app de Vue

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}